# Generated by Django 2.1.5 on 2019-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190215_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='web_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
