# Generated by Django 2.1.5 on 2019-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_job_web_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='web_address',
            field=models.URLField(),
        ),
    ]
